sudo: false
language: node_js
node_js:
  - "9.4.0"

env:
  global:
    - YARN_VERSION=1.3.2

before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

script:
  - yarn run eslint
  - yarn run test
  - yarn run flow
  - yarn run build
  - yarn run build-storybook

after_success:
  - ./node_modules/.bin/codecov

deploy:
  - provider: npm
    email: evenchange4@gmail.com
    api_key:
      secure: CVf16Aphbq6dJzvcBsSBswUw2UTJ1MSrDcG8fnYXeOusW5Z4/mq0Coq3aEXmH2qCUXOI23aQFA+2DhcEbM5sfTdRSDxaHFx6bYjyA+Sr4oQYgeucRX1oI01ef5ifDwWkaSIkWx1OoRGoaosssXvNROhRJkTgNoiyH+3muYWp8V0RwROPmxLkWIzZW6sO5H5ppnADrwkxQHjB2URSUV4T2xvt8uS4eODd7AMPUqdRasfwNH/W32XdKb4LzTxMwskcCNfnZf5AFwOScF+rjjs6kvjluq5RVIaCefklGlsR2DTof/DhCIxff0HaU3mdDy8aKJRREZysCTA6jF+Mx2sn/a+JpQnEURn6vYw0aU31bsQuvrHvTUBVX704ONZ4hDhFoVvxh+2XsLW/xEFw0aZacTkaosoBVejcu2Nbd/TBVUfQBj3nqdibda+5yrK7X0rOVbmgv6mlmsKKTpSU5NjGeOzPKKOs4eipqwjkDYdXYJaZyziNuH9CLLpiv2Sw0SokHsaZTyl+/NliLRJePuIUnT1ePxi70ZCAqgDImgqsQxRkWS8d1Vp/KGT0NxuZyYl8leY90RdeX/k7kGjA+o0zJ9Eg6iXJGv5pVfk5E9XNRQQZDSpYvwjX0/Nlva8tJMOXIyeuikJmV7uQbF6jQa/LyTh8yCYx7B4vZUNgl7t3Qpc=
    skip_cleanup: true
    on:
      tags: true
      repo: evenchange4/react-dnd-dropzone

cache:
  yarn: true
  directories:
    - "~/.yarn"
    - node_modules

notifications:
  email: evenchange4@gmail.com
